language: node_js

node_js:
    - 'stable'

cache:
    yarn: true
    directories:
        - node_modules

install:
    - yarn install --ignore-optional

services:
    - mongodb

before_script:
    - sleep 15
